server:
  port: ${PORT}
env:
  telegram:
    texts:
      path: texts/
    bot:
      name: ${BOT_NAME}
      token: ${BOT_TOKEN}
      baseUrl: https://api.telegram.org/bot
  commands:
    -
      name: main
      resourceId: main
    -
      name: fyodor1
      resourceId: bio1
    -
      name: fyodor2
      resourceId: bio2
    -
      name: fyodor3
      resourceId: bio3
    -
      name: fyodor4
      resourceId: bio4
    -
      name: dielo1
      resourceId: dielo1
    -
      name: dielo2
      resourceId: dielo2
    -
      name: varia
      resourceId: varia