server:
  port: ${PORT}
env:
  telegram:
    texts:
      path: texts/
    bot:
      name: ${BOT_NAME}
      token: ${BOT_TOKEN}
      baseUrl: https://api.telegram.org/bot
  commands:
    -
      name: main
      resourceId: main
    -
      name: aboutus
      resourceId: about_us
    -
      name: inpoland
      resourceId: in_poland
    -
      name: rutest
      resourceId: ru_test