env:
  telegram:
    texts:
      path: texts/
    bot:
      name: changeme
      token: changeme
      baseUrl: changeme
  commands:
    -
      name: main
      resourceId: main
    -
      name: aboutus
      resourceId: about_us
    -
      name: inpoland
      resourceId: in_poland
    -
      name: rutest
      resourceId: ru_test